### PR TITLE
Add inlets repo

### PR DESCRIPTION
**Pull request by alexellis**
This adds inlets and the inlets-operator from the same team as the 
OpenFaaS open source project. inlets is on the CNCF Landscape.

Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>

### CODE REVIEW

**Comment by alexellis** [comment]
This is definitely signed-off, there's a bug in your bot @rimusz ?

**Comment by rimusz** [comment]
@alexellis please update the file `repos.yam` as well

**Comment by alexellis** [comment]
Sure.. done.

**Comment by rimusz** [comment]
LGTM

**Comment by alexellis** [comment]
Thank you

**Pull request merged**
