### PR TITLE
Fix repos.yaml format and add check in CI

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by tamalsaha** [comment]
I am programmatically parsing repos.yaml into json and it fails as it stands in the master branch. This pr fixes the format and adds test using `yq` so that its format stays valid.

**Comment by tamalsaha** [comment]
Q: I have never used CircleCI before, how to run the check every time a pr is open? I know how to use Github actions.

**Comment by mattfarina** [comment]
@tamalsaha If you would like you can do it in GitHub Actions. We are starting to use those in places on the Helm project.

**Comment by tamalsaha** [comment]
Thanks, @mattfarina ! I have moved the validation check to Github actions. Please enable Github actions for this repo. It is working in my fork. PTAL.

**Pull request merged**
