### PR TITLE
Add docs on Artifact Hub migration

### PR DESCRIPTION
**Pull request by mattfarina**
Relates to #439

### CODE REVIEW

**Review by scottrigby — APPROVED** [review]
I think this is clear and to the point!

**Comment by scottrigby** [comment]
PS I would have said let's add some dates here, but I like the straightforwardness of this. It's a simple move for folks to make, artifact hub fixes lots of existing helm hub issues, the user experience is nicer – looking forward to getting this done as soon as we can 🙂

**Comment by mattfarina** [comment]
@scottrigby I don't think we have dates yet. We need to discuss that.

**Comment by tegioz** [comment]
A couple of notes regarding the manual handoff @mattfarina:

To transfer a repository manually, the user transferring it *must belong* to the destination organization. So one of the Helm organization members will need to be invited to the destination organization temporarily and leave it afterwards.

If the destination is not an organization but a user, the only way of transferring it manually would be to invite that user to the Helm organization, which is not probably what you'd like to do.

The reasoning this works this way is that the user doing the transfer must have permissions to create repositories in the destination entity. I think this is similar to how transferring repos in Github works.

**Pull request merged**
