### PR TITLE
Add Puppetserver Helm Chart

### PR DESCRIPTION
**Pull request by Xtigyro**
CC: @underscorgan @slconley @iristyle

### CODE REVIEW

**Comment by slconley** [comment]
Cool to see this being added...  glad to be a part of it!

**Comment by underscorgan** [comment]
🎉 🎉 🎉 and I'm with the pupperware (pupperware@puppet.com) team as well

**Comment by mattfarina** [comment]
The [Artifact Hub](https://artifacthub.io) is another place you can list your repos. To do that, you login (or create an account), create an organization, and list your repository. You can link it to a user or organization.

**Comment by Xtigyro** [comment]
@mattfarina Thank you! And it's been published Artifact Hub as well: https://artifacthub.io/package/chart/puppetserver/puppetserver-helm-chart

@underscorgan @slconley @iristyle

**Pull request merged**
