### PR TITLE
Add ERPNext chart repo

### PR DESCRIPTION
**Pull request by Thunderbottom**

### CODE REVIEW

**Comment by mattfarina** [comment]
The [Artifact Hub](https://artifacthub.io) is another place you can list your repos. To do that, you login (or create an account), create an organization, and list your repository. You can link it to a user or organization.

**Comment by mattfarina** [comment]
@revant are you ok being listed as a maintainer here?

**Comment by revant** [comment]
> are you ok being listed as a maintainer here?

Yes. I'm okay being listed as maintainer.

**Comment by Thunderbottom** [comment]
fixed the conflict, hope this works.

**Pull request merged**
