### PR TITLE
Add openfaas helm chart

### PR DESCRIPTION
**Pull request by LucasRoesler**
Adds OpenFaaS Helm chart to the list

### CODE REVIEW

**Comment by mattfarina** [comment]
@alexellis since you are listed as the contact on this can you please provide your approval here before we merge

**Comment by alexellis** [comment]
Hi folks what do we need to do to get this merged?

Alex

**Comment by alexellis** [comment]
@mattfarina are we good to go now?  😄

**Comment by scottrigby** [comment]
@alexellis About this:
> I would have liked to have seen the maintainers mirrored from the upstream helm chart repo though

Do you mean you'd like to add @rimusz like he's listed here? https://github.com/openfaas/faas-netes/blob/master/chart/openfaas/Chart.yaml#L16 Just clarifying… if so, it's a pretty easy addition. I don't want to bikeshed this though, it's good to go otherwise.

**Comment by alexellis** [comment]
Please accept it as-is, we can adjust the list in-flight. For context I think the original PR only had me listed as a maintainer. 

Alex

**Comment by alexellis** [comment]
Thank you! 👍

**Comment by alexellis** [comment]
I just noticed something - a non-upstream openfaas helm chart in the hub?

https://hub.helm.sh/charts/banzaicloud-stable/openfaas

**Comment by scottrigby** [comment]
Yeah, that's an interesting thing about the hub. It points to multiple Helm repos that each may host versions of a chart for the same app. We will need to 1. make crystal clear where the chart is coming from (https://github.com/helm/hub/issues/40), and 2. probably add some way to show usage (GitHub repo stars, potentially number of downloads, etc) - maybe other things. We've discussed these, but issues/PRs is probably the best place to discuss details about and implications of each.

**Pull request merged**
