### PR TITLE
Add choerodon helm repo

### PR DESCRIPTION
**Pull request by vinkdong**
Add helm repo for [choerodon](https://github.com/choerodon/choerodon) project.

### CODE REVIEW

**Comment by mattfarina** [comment]
@vinkdong I noticed all the descriptions read "A Helm chart for Kubernetes". It would be worth putting a real description on the charts.

**Comment by vinkdong** [comment]
@mattfarina  Thanks for pointing, I will improve it as soon.

**Comment by vinkdong** [comment]
@scottrigby Thanks for reminding us, we have deprecated our prometheus-operator.

**Comment by scottrigby** [comment]
@vinkdong Thank you 💯

**Pull request merged**
