### PR TITLE
add saikatharryc & volantmq repo

### PR DESCRIPTION
**Pull request by saikatharryc**
Signed-off-by: Saikat Chakrabortty <saikatchakrabortty2@gmail.com>

### CODE REVIEW

**Comment by saikatharryc** [comment]
@4nte

**Comment by mattfarina** [comment]
@saikatharryc The [Artifact Hub](https://artifacthub.io) is live. You can also list your Helm repos there. To do that, you login (or create an account), and list your repository. You can link it to a user or organization.

**Comment by saikatharryc** [comment]
@mattfarina it's not present there I believe! 
it needs to merge before?

**Comment by mattfarina** [comment]
@4nte and @saikatharryc are you ok being listed as maintainer for this Helm repo?

**Comment by 4nte** [comment]
> @4nte and @saikatharryc are you ok being listed as maintainer for this Helm repo?

Sure!

**Comment by mattfarina** [comment]
@saikatharryc The artifact hub is another place to distribute things. It's separate.

@4nte thanks for the quick response.

**Pull request merged**
