### PR TITLE
Added Aerokube charts repository

### PR DESCRIPTION
**Pull request by vania-pooh**

### CODE REVIEW

**Comment by vania-pooh** [comment]
Please suggest whether I need to gpg sign my commit.

**Comment by mattfarina** [comment]
@vania-pooh For the [Developer Certificate of Origin](https://developercertificate.org/) that Helm uses you need to signoff. This is different from crypto signing. No PGP keys are needed. It's where you signoff that you have permission to contribute these materials. The _checks_ tab at the top has the commands needed to correct your existing commits. This is based on the `--signoff` flag.

**Comment by vania-pooh** [comment]
@mattfarina done.

**Comment by mattfarina** [comment]
The [Artifact Hub](https://artifacthub.io/) is another place you can list your repos. To do that, you login (or create an account), create an organization, and list your repository. You can link it to a user or organization.

**Pull request merged**
