### PR TITLE
Adding DandyDeveloper charts (Github Pages)

### PR DESCRIPTION
**Pull request by DandyDeveloper**

### CODE REVIEW

**Comment by mattfarina** [comment]
@ssalaues are you ok being listed as a maintainer on this charts repo?

**Comment by DandyDeveloper** [comment]
@mattfarina Worth noting, @ssalaues has been a bit MIA as of recent, but he was the original maintainer here: https://github.com/helm/charts/blob/master/stable/redis-ha/OWNERS

I'd be happy to remove him for the time being if it means getting this in quicker.

**Comment by mattfarina** [comment]
@DandyDeveloper I don't want to add him as a maintainer without his consent. It's ok to change and add him later.

**Comment by DandyDeveloper** [comment]
@mattfarina Removed him for the time being. Thank you!

**Comment by ssalaues** [comment]
Thanks for asking @mattfarina totally okay being added

**Comment by DandyDeveloper** [comment]
Readded!

**Pull request merged**
