### PR TITLE
Concourse chart

### PR DESCRIPTION
**Pull request by pivotal-bin-ju**
Request to add concourse to `helm/hub`

### CODE REVIEW

**Comment by pivotal-bin-ju** [comment]
Hi @mattfarina,
Thanks for your suggestion for setting up the repo which is capable to have multiple charts. We've noticed this. For `concourse` we only have one chart, that's why we have a singular name `concourse-chart`. If you have more concern please let me know.

**Comment by mattfarina** [comment]
@pivotal-bin-ju I'm sorry if there has been some confusion on our part. Let me try to explain.

The Helm Hub does not take a URL to a specific chart in a Git repo. Instead it needs to look at a Helm Repo which has certain characteristics. The most important is an `index.yaml` file containing details about each chart and chart version. Even if you have a single chart we expect it to be released with different semantic versions over time. The `index.yaml` file for a repo will point to the location to fetch the chart as a `.tgz` file that was created by the `helm package` command. Optionally, there can be a provenance file for those who want signing and verification looped in.

If you are going to do this with GitHub there are docs on how to do it at https://github.com/helm/hub/blob/master/docs/github.md

**Comment by pivotal-bin-ju** [comment]
Hi @mattfarina ,
Thanks for the explanation!

In our PR, we've setup the repo on `gcs`.
```yaml
- name: concourse-chart
  url: https://concourse-chart.storage.googleapis.com/
```

Here is the content at `https://concourse-chart.storage.googleapis.com/`

```xml
<ListBucketResult xmlns="http://doc.s3.amazonaws.com/2006-03-01">
  <Name>concourse-chart</Name>
  <Prefix/>
  <Marker/>
  <IsTruncated>false</IsTruncated>
  <Contents>
     <Key>concourse-8.2.6.tgz</Key>
     <Generation>1573165258576388</Generation>
     <MetaGeneration>1</MetaGeneration>
     <LastModified>2019-11-07T22:20:58.576Z</LastModified>
     <ETag>"00a7fb05b1a583c831d76f9ae6d916e5"</ETag>
     <Size>66499</Size>
  </Contents>
  <Contents>
     <Key>index.yaml</Key>
     <Generation>1573165254258916</Generation>
     <MetaGeneration>1</MetaGeneration>
     <LastModified>2019-11-07T22:20:54.258Z</LastModified>
     <ETag>"15fa6d815261fbbbef896acbef50b5fa"</ETag>
     <Size>824</Size>
  </Contents>
</ListBucketResult>
```
Maybe the repo name confused you. We have the github repo `concourse/concourse-chart` (singular) which hosts the source code of the chart(We have only one chart). while the `gcs` bucket `https://concourse-chart.storage.googleapis.com/` is for helm chart repo. we've filled this url as chart repo in the PR for exposing our helm chart.
Please correct me if anything is incorrect.

**Comment by pivotal-bin-ju** [comment]
@mattfarina There was some confusion between what myself and another colleague were doing. We've cleaned up the branch and are using GCS to host our chart repository. Let us know if there's anything else we are missing. Thank you!

cc @taylorsilva

**Pull request merged**
