### PR TITLE
[WIP] Adding GitHub pages docs

### PR DESCRIPTION
**Pull request by mattfarina**

### CODE REVIEW

**Comment by jdolitsky** [comment]
Should we mention https://github.com/helm/chart-releaser ?

**Comment by davidkarlsen** [comment]
LGTM

**Comment by scottrigby** [comment]
For now, I like it! Consolidates some of the bits and pieces I've read elsewhere in a clear way. 

Though TBH this PR is kind of a motivator for us to finish the GitHub app (working on it!) because then the directions could be something as simple as:
> 1. Install the NAME GitHub app in your [organization](https://help.github.com/articles/installing-an-app-in-your-organization/#installing-a-github-app-in-your-organization) or [personal account ](https://help.github.com/articles/installing-an-app-in-your-personal-account/#installing-a-github-app-in-your-personal-account)
> 2. Enable in your repo
> 3. Push changes to your chart, and enjoy!
> 4. For advanced features, see the [example config file](#)

**Comment by scottrigby** [comment]
@joshisa I was thinking the same thing, but thinking we want to finish the GitHub app and make it available first. Honestly I kind of would like to do that before adding this README, but you know I think this is accurate and can help people so why not iterate on the README as more options become available 🤷‍♂️

**Comment by scottrigby** [comment]
Or I see what you mean, perhaps a short link to the project, prior to the app side of it. I agree why not 👍

**Comment by rimusz** [comment]
looks good, +1 adding short link/description  to `[chart-releaser](https://github.com/helm/chart-releaser)`, the rest can be added later one

**Comment by mattfarina** [comment]
@jdolitsky, @paulczar, or anyone else... is chart-releaser ready for production use? I didn't include it in the first go because I didn't see a release tag and I know we'd been talking about doing a SaaS.

Is it ready to include at this time?

**Comment by mattfarina** [comment]
@scottrigby I like the app motivation. All of these docs and things can continuously iterate. I expect the docs to all improve over time and I encourage it. This is just a starting point.

**Comment by jdolitsky** [comment]
Im not sure. Im in favor to also merge and add something later on! didnt mean to derail

**Comment by unguiculus** [comment]
I think this looks good for now. Personally, I'd prefer using releases instead of a docs folders, but this is more complicated. [chart-releaser](https://github.com/helm/chart-releaser) will help with that but it's in early stages and not very well tested yet. IMO, we should not link to it yet.

**Comment by scottrigby** [comment]
Agree, let's merge now and iterate. Thanks @mattfarina !

**Pull request merged**
