### PR TITLE
Add KubeInvaders Helm Chart

### PR DESCRIPTION
**Pull request by lucky-sideburn**

### CODE REVIEW

**Comment by rimusz** [comment]
LGTM

**Comment by lucky-sideburn** [comment]
Hi @mattfarina thank you :)

I added https://lucky-sideburn.github.io/helm-charts/index.yaml as you suggested.

**Comment by lucky-sideburn** [comment]
Hi @mattfarina is it ok my index.yaml? :)

**Comment by mattfarina** [comment]
@lucky-sideburn Your index.yaml file is in the proper format but does not list any charts in it so your charts will not display in the Helm Hub.

To see what I mean try running `curl -L https://charts.bitnami.com/index.yaml`. You can see the `index.yaml` file that Bitnami has.

The locations for the charts do not need to be in the same repo but they do need to be listed. Do you have charts you want listed? 

In addition to the docs I listed earlier there is also https://helm.sh/docs/howto/chart_repository_sync_example/

**Comment by lucky-sideburn** [comment]
Hi @mattfarina !

Sorry fo my delay.. I updated https://lucky-sideburn.github.io/helm-charts/index.yaml as you suggested :)

**Pull request merged**
