### PR TITLE
Add eclipse-iot packages project

### PR DESCRIPTION
**Pull request by axdotl**
Signed-off-by: Axel Köhler <axel.koehler@kiwigrid.com>

* Add repo for the eclipse IOT packages project (<https://www.eclipse.org/packages/>)

### CODE REVIEW

**Comment by mattfarina** [comment]
@ctron @thjaeckle are you ok being listed as a maintainer on this?

**Comment by thjaeckle** [comment]
@mattfarina ok from my side

**Comment by ctron** [comment]
@mattfarina yes sure. I think it would make sense to add @calohmn as well, as he is a project lead on the Eclipse IoT Packages project as well [1].

[1] https://projects.eclipse.org/projects/iot.packages/who

**Comment by axdotl** [comment]
I updated the branch and added @calohmn

**Pull request merged**
