### PR TITLE
Added Soluto's repo

### PR DESCRIPTION
**Pull request by omerlh**

### CODE REVIEW

**Comment by philoserf** [comment]
There appears to be an issue with the gh-pages branch. As of this moment the rsult is an HTTP404.

**Comment by omerlh** [comment]
yep just tested it and find the same thing, sorry, will update once I manage to fix that

**Comment by prydonius** [comment]
I'm able to get to `https://charts.soluto.io/index.yaml` just fine, that's all the Helm Hub needs to get your charts!

**Comment by omerlh** [comment]
Yep, just find it - I used helm to verify:
```
helm repo add soluto https://charts.soluto.io
```

**Comment by omerlh** [comment]
How does the deployment process work? When does the hub fetch updates from the repositories? I couldn't find a documentation for that

**Pull request merged**
