### PR TITLE
Add repo for k8s-cloudwatch-adapter

### PR DESCRIPTION
**Pull request by chankh**
Add helm chart repo for awslabs/k8s-cloudwatch-adapter#49

### CODE REVIEW

**Comment by mattfarina** [comment]
@chankh Can you please add this repo to the Artifact Hub before we merge it here. The Helm Hub is migrating to the Artifact Hub. You can find details at https://github.com/helm/hub#artifact-hub-migration

**Comment by chankh** [comment]
@mattfarina Also added to Artifact Hub, here is the link https://artifacthub.io/packages/helm/k8s-cloudwatch-adapter/k8s-cloudwatch-adapter

**Comment by mattfarina** [comment]
@chanck you might want to change the description on the chart from the default of "A Helm chart for Kubernetes". That's what will be displayed by hubs.

**Review by mattfarina — APPROVED** [review]
lgtm

**Pull request merged**
