### PR TITLE
Add Longhorn repo

### PR DESCRIPTION
**Pull request by ttpcodes**
@yasker

### CODE REVIEW

**Comment by mattfarina** [comment]
The [Artifact Hub](https://artifacthub.io/) is another place you can list your repos. To do that, you login (or create an account), create an organization, and list your repository. You can link it to a user or organization.

**Comment by mattfarina** [comment]
@yasker are you ok being listed as a maintainer here? Is it ok to list the longhorn maintainers here?

**Comment by yasker** [comment]
@mattfarina Yes, I am ok with listing myself and longhorn maintainers here.

And thanks for the information on Artifact Hub, we will work on that too.

**Comment by yasker** [comment]
Thanks Matt!

**Pull request merged**
